### ISSUE TITLE
默认校验文件生成的路径不是在当前目录的bad子目录下吗？

### ISSUE THREAD

**Issue by le45tx1m** [zanjie1999/fixBadDisk#1]
一开始没看说明，Windows版本直接在<users>\Downloads目录下双击执行了，想删除校验缓存，但是Downloads目录下没找到bad文件夹，到根目录也没找到，所以来求助默认会生成在哪？

**Comment by zanjie1999** [comment]
会默认生成在当前运行的目录下的bad文件夹中，没有找到那就是压根没开始跑
